### ISSUE TITLE
RFC006: How to handle deactivation cascading

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-specification#100]
When deactivating a service provider, what should be done with the care providers and the issued credentials?
A deactivated document loses the compound services which can still be refered to.
The OrganizationCredentials are still valid, and care providers are still findable. Which seems counter intuitive.

**Comment by woutslakhorst** [comment]
Orphaned DIDs should be prevented, preferable by transaction rules.

**Comment by woutslakhorst** [comment]
It can not be enforced by transaction rules (parallel transactions).

**Comment by woutslakhorst** [comment]
When a DID gets deactivated:

- credentials are no longer trusted when issued by that DID
- DID Documents that only have deactivated DIDs as controller are to be regarded as deactivated

consequences:

- when resolving a DID Document, also check if it has an active controller.
- when validating a credential, check if the DID isn't deactivated.
- when searching for credentials, validate found credentials => not-valid if issuer is deactivated.
- when deactivated, untrust that DID
