### ISSUE TITLE
RFC006 DID creation vulnerability

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-specification#115]
We have an attacker Eve which creates two DID Documents using the same keys. One DID Document has an added assertion key, the other has not. Eve will publish these DID Documents as two transactions. Both as create transactions with a JWK.

Other nodes will receive the transactions is some order.
We currently have no definition on when a TX is an update of a DID Document or a create. Neither do we have specified what should be done when two TXs create the same DID Document, but with different contents.

The current Nuts node will detect an update based on DID existence (not by checking jwk/kid header), meaning that the second DID Document received will not be updated in the VDR. When the assertion key is used to sign TXs, some nodes will not process the transaction since they do not have the assertion key, others will....

This is not a problem when the nuts-node is the only implementation. But it's an attack.

Solutions:
- define behaviour for parallel creates (with merges)
- use hashes to determine the DID (hash of DID Document without ID field). This also requires different identifiers for the keys and services. Prefixes of the DID are no longer possible for key material. Requires an extra DB search: KID to DID Document.

**Comment by woutslakhorst** [comment]
The current nuts-node update/create detection is wrong. It should use the presence of kid/jwk and then also merge on duplicate creates.

**Comment by reinkrul** [comment]
To add for DID creates: if it already exists, merge it (section 5.1). Already implemented in the Nuts Node.
