### ISSUE TITLE
Node ID, peer discovery, private transactions

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-specification#116]
The NutsAuthorizationCredential requires one additional feature: private transactions or "how to answer a payload request for private transactions"

The idea is to have the transaction itself being public (backup and distribution) but to have the payload private.
To enable this a bunch of other features are needed.
I'll list them in order of implementation

## Node ID

The first step is to change the uuid identifier of a node to a key pair. The public key fingerprint will be the new identifier (base58 encoded). A node can generate this key pair automatically. Only one should exist until the node has a DID Document. The node sends this identifier the same way it does now. It should also send a `nonce` and a `signature` (using private key over the nonce). 

## DID Document per node

Next, generate a DID Document for each node. This is a manual step since the controller has to be selected (didman can help in this). For a new network this step can only be done after the first few nodes have connected and only after a root TX has been generated. The node ID will now change from just the fingerprint to a `did:nuts:` type identifier. (this would require a node restart to effectuate on the connection.... a small todo).

## Add keys to the DID Document

The node DID Document would require `assertionMethod` and `keyAgreement` keys. The first will be used as additional signature on a transaction and the latter will be used for encrypted relay in a partial mesh.

## Add services to the DID Document

For peer discovery, the DID Document should add:

```
{
    "id": "did:example:123456789abcdefghi#id",
    "type": "DIDCommMessaging",
    "serviceEndpoint": "grpc://example.com:5000",
    "accept": ["didcomm/v2"]
}
```

This will connect the address of a node to its ID.

## Connect nodes to care organizations

A DID Document for a care organization can then refer to the node endpoint:

```
{
    "id": "did:example:123456789abcdefghi#didcomm-1",
    "type": "DIDCommMessagingMediator",
    "serviceEndpoint": "did:example:123456789abcdefghi?type=DIDCommMessaging"
}
```

The different type for a care organization is to aid in searching for the right endpoints (eg only `DIDCommMessaging`) when nodes try to find peers. The DID usage in the serviceEndpoint is the same as used now for other service endpoints.

## Add TX support

We now have nodes with an identity and we can find the nodes that serve a particular care organization. The next step is to add an addressing field to a transaction. The `to` header field (in line with DIDCom) should be added which contains a list of recipients. An entry would be a DID of a care organization.

A payload request must get an optional `from`, `once` and `signature` field. Or add a JWS or switch to DIDCom for this message type. The `from` would be the DID of the care organization. The signature should be set using an `assertionMethod` key of the care organizations DID Document. The receiver of the request can check if the required data is private and if the requestor matches the DID from the `to` field of the transaction. If it matches, it'll send the payload to a node that is referenced by the DID Documents `DIDCommMessagingMediator` service.

## Change all messages to DIDCom

Replace all message types with DIDCom. If all messages need to be signed depends on if we want to support anonymous nodes. These would be nodes without a DID Document.

## Support partial meshes

We can now support partial meshes and private transactions using https://identity.foundation/didcomm-messaging/spec/#routing

**Comment by reinkrul** [comment]
Maybe the nonce (to be signed) should be sent by the party receiving the connection instead of the peer making up its own nonce, since that may open up replay attacks (stealing a signed nonce, then using it). Maybe add hash of used TLS certificate.

**Comment by woutslakhorst** [comment]
adding the hash of the TLS cert will work

**Comment by woutslakhorst** [comment]
Fixed by RFC015
