### ISSUE TITLE
RFC006: incorrect content type

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-specification#120]
In 3.2.1 and several examples we have the following content type
> - `cty` MUST contain the value `application/json+did-document`

According to did-core-specs this should be `application/did+json` or `application/did+ld+json`

Not sure what to change it to since nuts-node implementation uses did+json, but examples in the RFC are did+ld+json

**Comment by woutslakhorst** [comment]
just has to be changed to `application/did+json` in spec. Impl is ok

**Comment by reinkrul** [comment]
Already fixed by https://github.com/nuts-foundation/nuts-specification/pull/121
