### ISSUE TITLE
RFC003: oauth usi vs vcs

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-specification#132]
usi is base64 encoded and vcs is just json. Pick one already.

**Comment by woutslakhorst** [comment]
start on this after the next two workshops ~ 1st of December. Since this change will induce API changes, which will also require manual changes. There's no rush...

**Comment by woutslakhorst** [comment]
The VC and VP standard is getting some more traction, we therefore change from using b64 encoding for both fields to using the JSON notation.

**Comment by reinkrul** [comment]
Already fixed.
