### ISSUE TITLE
RFC017: Set reconciliation cannot resolve IBLT collision on a single page

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-specification#164]
Assume a node is missing 2 transactions from a peer that happen to cause a collision on a single page.

A node will keep asking its peer for IBLTs to resolve the difference. Each request will be for an IBLT one page lower. The node will be able to decode the IBLT up to one page below where the collision occurs. The node can conclude that the collision is on the next page and request the entire page from the peer.

Last paragraph of §6.2.3
> If the decoding fails, the local node sends a new State message. The IBLT subtraction used the range 0-min(LC, LC_req). The new request MUST be for one page lower. The LC value MUST be the end of that previous page. The XOR value MUST be calculated over the transaction references in the range starting with 0 and ending with the new LC value.

Since the peer will conclude that the XOR over this shorter LC range matches its own XOR over this range, it will not respond to the `State` message. The node will therefor not receive the IBLT needed to conclude where the collision is.

**Comment by gerardsn** [comment]
possible solutions:
1. the peer compares the XOR (over the shorter LC range) in State to the XOR of its entire DAG. (I might be misinterpreting the spec and this is already what should happen) There is limited benefit for this case since a node initiates set reconciliation when its LC is lower than that of its peer, so the XORs should never match.
2. the peer sends a response to inform the node that they are in sync.
3. XOR in State is for the node's entire DAG. If the set difference has been resolved some other way during set reconciliation the peer can stop the reconciliation process.
4. XOR removed from State and peer MUST respond with an IBLT over the requested range.

I prefer option 2 and 3 since they prevent a node from requesting an entire page for no reason.

**Comment by woutslakhorst** [comment]
Doesn't §6.2.4 describe the solution to your problem?

**Comment by gerardsn** [comment]
I don't think it does. The way I read this, if the node and peer have the same XOR over the smaller range, the peer will ignore the State message (§6.2.2). So the node doesn't receive the IBLT that it needs to do what is described in §6.2.4

**Comment by gerardsn** [comment]
Alright, so it already is option 1.

Comparing the XORs this way has limit value. For this XOR comparison to short-circuit set reconciliation, the transactions in the LC range requested by the node in State should exactly match the total LC/DAG state of the peer. 

State can be sent 
1. in response to Gossip, but only when peer sending the Gossip has an LC larger than the node. This is the exact opposite situation of what is needed, so XORs will never be the same.
2. when receiving a Tx for which prevs are missing. 

If all goes well, case 1 should occur most frequently. But even in case 2, it is unlikely that the XORs will ever be the same if you account for limitations that come with using pages.

In its current form, XOR comparison during set reconciliation only creates extra work. (for nodes and developers)

**Comment by woutslakhorst** [comment]
I think you're forgetting branches where multiple TXs have the same LC value.

**Comment by woutslakhorst** [comment]
An optimization can be done at a later stage where Bob can respond without an IBLT in response to a State message from Alice. This could be used when a IBLT decode fails for Alice but when the previous page is entirely up2date.

**Comment by gerardsn** [comment]
fixed by #176
