### ISSUE TITLE
RFC017: XOR in state is confusing

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-specification#175]
https://github.com/nuts-foundation/nuts-specification/blob/9f633d07d245b16f077e2fbb7fd8835ccc46faae/rfc/rfc017-distributed-network-grpc-v2.md?plain=1#L270

The line above is confusing and conflicting because
- the description of `State` msg states that the XOR should be over the entire DAG.
- the peer always compares this XOR to that of its entire DAG, so the values under comparison do not (always) have the same meaning.

Proposal:
Change it so `State` always contains the XOR of the entire DAG, and the LC reflects the range to compare.  
This also creates a circuit breaker in case both DAGs get back in sync during set reconciliation.

**Comment by woutslakhorst** [comment]
In addition to your remarks (which are correct):

- `State` should only be sent in response to a Gossip. A `State` message can be seen as a IBLT request.
- `State` is not sent at regular intervals (although it wouldn't damage anything)
- `State` is not sent by a node that is ahead (based on LC). Which means LC needs to be added to the Gossip message as well. If Alice has 1 new TX and gossips this to Bob. Bob gossips no new TXs to Alice but its XOR is different to that of Alice. Alice will send a State message with current logic. This is not needed and would be very common.
- `State` MUST be sent when prev transactions are missing when received over Gossip.

**Comment by woutslakhorst** [comment]
Decision:

- XOR value must always be XOR of entire TX state
- State message must not be sent periodically
- State message is sent as response to XOR mismatch of missing prevs
- when processing Gossip: missing TX must be requested. But also calculate new XOR based on old XOR with hashes of requested TXs. (Check LC value)
- If a node is ahead (LC wise) do not sent a State message
