### ISSUE TITLE
RFC014: Add json-ld context information

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-specification#211]
Currently the context is only mentioned in the example section, this needs a separate chapter.

Also, use the updated `v2` context which includes missing fields. See https://github.com/nuts-foundation/nuts-node/issues/1452.

**Comment by woutslakhorst** [comment]
waiting for: nuts-foundation/nuts-node#1453

**Comment by woutslakhorst** [comment]
Covered by RFC011 §3.1
