### ISSUE TITLE
Sync wcs JOSE with new wc from W3C

### ISSUE THREAD

**Issue by pascaldekloe** [nuts-foundation/nuts-specification#220]
There's an [upcoming recommendation](https://w3c.github.io/vc-jwt/) from the W3C for embedding "verifyable credentials" into JOSE headers. We may want to adjust RFC003 accordingly.

**Comment by woutslakhorst** [comment]
That recommendation is about representing a VC as JWT not using multiple VCs in a JWT.

**Comment by woutslakhorst** [comment]
no, we have an auth request containing VCs and other claims, not just one VC
