### ISSUE TITLE
RFC017: Private TX handling of TransactionListQuery is ambiguous

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-specification#230]
https://nuts-foundation.gitbook.io/drafts/rfc/rfc017-distributed-network-grpc-v2#5.2.3-transaction-list states:

> All transactions in the TransactionList message MUST be sorted by LC value (lowest first). All transactions without a pal header MUST be added with their payload. Transactions with a pal header are discussed in [§7](https://github.com/drafts/rfc/rfc017-distributed-network-grpc-v2#7-private-transactions).

Leaves up to interpretation what to do with transactions with private payloads.

**Comment by woutslakhorst** [comment]
"Payloads for transactions with a PAL header MUST not be added"
