### ISSUE TITLE
'Legal Base' should be 'Legal basis' and align with the legal definition. (RFC001 Nuts Start Architecture)

### ISSUE THREAD

**Issue by CiolinaNictiz** [nuts-foundation/nuts-specification#248]
I noticed _both_ the terminology _and_ definition in [RFC001 ](https://nuts-foundation.gitbook.io/v1/rfc/rfc001-nuts-start-architecture#2.-) deviates from established legal texts, specifically the GDPR.

Terminology:
'Rechtsgrond' translates to 'Legal basis', not 'Legal Base'. This may be verified by comparing the English and Dutch texts of the GDPR,  where the term first appears in consideration 41 of the opening statement (and then throughtout the document). 

N.B. Permission as used in Wabpvz art. 15a doesn't provide a legal basis for exchange of medical data (just index sharing), so Wabpvz definition of permission does not apply.

Definition:
The current definitionof Legal Base in RFC001 ends with 'By default, no medical data may be exchanged'. This conforms to [Article 9, paragraph 1 of the GDPR](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=EN#d1e2051-1-1). 

However the opening ('Grounds ... given by the subject ...')  implies a data subject must assign the legal grounds for processing of their personal (health) data. This is wrong, as [technically _the controller_ must establish the legal basis](https://www.bing.com/search?q=who+determines+the+legal+basis+for+processing+of+personal+data) before they process data to achieve a specific goal! 
It also, wrongly,  implies only consent as defined in [GDPR article 9](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=EN#d1e2051-1-1), paragraph 2, point A can be used to process medical data,  ignoring point B to J of the same paragraph. These provide many more possible legitimizations, most _without_ the explicit dependance on other laws present in point A.

I suggest removing the reference to consent and changing to: 'Grounds for medical data exchange conforming to national and international legislation.'

**Comment by woutslakhorst** [comment]
Thank you for your feedback. I made some changes in #249. Could you review them?
