### ISSUE TITLE
RFC004: Add signingtime requirements

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-specification#27]
The header of the document contains a signing time `sigt` property. Is it allowed for this timestamp to lay in the future? If so, how far?

**Comment by woutslakhorst** [comment]
https://en.bitcoin.it/wiki/Block_timestamp maybe

**Comment by reinkrul** [comment]
No requirements for signing time because it adds no additional security. Check implementation for conformance.

**Comment by woutslakhorst** [comment]
SHould be referred to from #49
