### ISSUE TITLE
RFC004: remove timeline ID and version

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-specification#30]
was required for patch style updates

**Comment by woutslakhorst** [comment]
see #36

**Comment by woutslakhorst** [comment]
Branching is a problem for consistency. Consider DID Document updates. If a historic branch is received at a later date and the given DID Document should have been the active version: all later VCs and documents must be considered in context of the new update. That would require some nasty complex algorithms to fix and will render some actions invalid that may already have been done.

A solution is to demand every tx content-type to be made of CRDTs (https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type). That would allow for any branched state to resolve to a consistent state without any reprocessing of the resulting DAG.

Examples:

- VCs can be considered as a Two-Phase Set. When a VC is issued it is static and can no longer be changed. It can be revoked, but that would place an entry in the 'tombstone set'. 
- DID Documents are a bit harder to solve. But parts of a DID Document can be considered as a Grow-Only set. Everything in a DID Document that is a list will be a G-Set. When a branch happens, those sets will be constructed as the union of the two branches. This will make sure that any key material will be trusted and future VCs will be valid. It could potentially be a problem for services: multiple services of the same type could be active with a different endpoint. In that case the client should retry any action on the other endpoint if one fails. If a service provider has left the old endpoint active, this won't be a problem and will help the service provider in identifying the problem.

To resolve a branch/union a new update tx must be provided referring to both previous transactions. This would also be a requirement for all updates: next to the heads the tx must also refer to the previous update transaction.

**Comment by woutslakhorst** [comment]
service updates are still problematic since they are updates for the same ID.

**Comment by woutslakhorst** [comment]
Service updates will have to be compliant to some sort of CRDT. In the DID-Core spec, IDs of services MUST be unique. This would add the requirement that service IDs have to be derived from the actual content. This would also mean that a service endpoint can not be changed without changing the ID. That would turn the services to a G-Set as well.

Concrete:
the service ID is the shaX of the service JSON without the ID. If an endpoint service changes, all compound services will have to change as well. (This would make a partial migration possible btw). It'll be left to the client to sort out which service to use in case of duplicates.

**Comment by reinkrul** [comment]
> Service updates will have to be compliant to some sort of CRDT. In the DID-Core spec, IDs of services MUST be unique. This would add the requirement that service IDs have to be derived from the actual content. This would also mean that a service endpoint can not be changed without changing the ID. That would turn the services to a G-Set as well.
> 
> Concrete:
> the service ID is the shaX of the service JSON without the ID. If an endpoint service changes, all compound services will have to change as well. (This would make a partial migration possible btw). It'll be left to the client to sort out which service to use in case of duplicates.

My first reaction;

Although I like the immutability of this concept, this is not very friendly in SaaS-like environments: having compound services refer to a specific version of a service, and having to recreate it when the concrete endpoint (probably residing in the controller's document) changes kinda defeats the purpose of having the separation of compound/concrete endpoints. Since when the concrete endpoint changes, you have to fix all referring compound endpoints.

I haven't thought of a better solution yet, though...

**Comment by woutslakhorst** [comment]
compound vs concrete endpoints would indeed have little value. So the compound services could have URLs in their references and not be limited to the concrete endpoints.

Note: in our current prod environment this is also the case.

**Comment by woutslakhorst** [comment]
implements services as immutable => use URI queries to select service from *parent*
