### ISSUE TITLE
RFC for support and status endpoints

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-specification#35]
Every service provider should offer contact information to the network how to reach them.
We should add an RFC which describes the usage of DID documents services for email and phone numbers and nuts node status endpoints for node status.

**Comment by reinkrul** [comment]
If we specify the status endpoint (URL), we should also specify what must be returned on the status endpoint

**Comment by stevenvegt** [comment]
Specify endpoints for email and phone.
Specify that every DID should have a resolvable support/contact endpoint (could be via a chain of controllers).

**Comment by reinkrul** [comment]
Node contact info in DID:

```json
{
  "id": "did:nuts:6WMVJvEgrRkQdpRUDTJQWHTEdT9DUsdTZgifXEo5z2k3#hash123456",
  "type": "node-contact-info",
  "serviceEndpoint": {
    "name": "Ad Ministrator",
    "email": "administrator@nuts.node",
    "telephone": "00316123456",
    "website": "https://www.nuts.node"
  }
}
```

I'd say only `email` is required, rest is optional. You can also refer to another DID:

```json
{
  "id": "did:nuts:6WMVJvEgrRkQdpRUDTJQWHTEdT9DUsdTZgifXEo5z2k3#hash123456",
  "type": "node-contact-info",
  "serviceEndpoint": "did:nuts:some-other-did?type=node-contact-info"
}
```

**Comment by reinkrul** [comment]
FIxed.
