### ISSUE TITLE
RFC006: Update Revocation with services and other keys

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-specification#37]
Update [RFC006 section 3.2.4](Retrieve Unlocks) Delete, with how to handle services and other verificationMethods such as assertionMethods.

Proposal is to update the document with an empty document which only contains the DID id.
Explain that information still in the DID can never be changed and will become out of date, so delete everything. If you want to know more, look back to previous versions of the DID.

**Comment by stevenvegt** [comment]
Ok, since we have the history we can always look back in time.

**Comment by woutslakhorst** [comment]
Already done

**Comment by stevenvegt** [comment]
In the current spec, it is optional to removing services, this should be updated.
