### ISSUE TITLE
RFC006: usage of controllers

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-specification#39]
Do we accept nested controllers? If so or if not, lets be clear about it in the spec.
Do we accept recursive controllers?

**Comment by woutslakhorst** [comment]
My initial thoughts are: just 1 lvl of controllers:

a SaaS provider may add a controller with an offline key as backup.
The provider also controls customer documents through its own did. This should not mean the backup key also directly controls the customer did documents.

**Comment by reinkrul** [comment]
I know the implementation currently (sort of) supports multiple levels, but for the sake of simplicity maybe we should just allow 1 level?

**Comment by stevenvegt** [comment]
Conclusions:
* no chain of of controllers, 1 level max
* instead of authenticationMethod use the capabilityInvocation for signing network transactions.
* No recursion in controllers (follows from point 1).
