### ISSUE TITLE
RFC005: Retrieve transaction payload from other nodes if queried peer doesn't have it

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-specification#59]
Currently the node queries the peer who sent the containing transaction for the payload, but for technical reasons the peer might not have it. Or it can't respond at that moment (network outage/crash/etc). In that case the node should try to retrieve the payload from another peer.

**Comment by woutslakhorst** [comment]
I'd suggest to handle the entire getHeads + Payload as an atomic operation. Then processing the TXs fails for that node but will be picked up from another node.

Handling it as an atomic operation is also required for disconnect + rollback

**Comment by reinkrul** [comment]
Maybe better to have the peer respond with both transaction + payload in 1 message in that case

**Comment by woutslakhorst** [comment]
> Maybe better to have the peer respond with both transaction + payload in 1 message in that case

hmmm, otherwise the async nature is making things very complicated....
we could also define the getPayload as a sync `rpc` call with a response?

**Comment by reinkrul** [comment]
We could, although that's not how the gRPC service is structured. In that case we should consider changing all request-reply-style calls to actual RPC request/reply calls. It would complicate things on gRPC level though since we have the single bidirectional gRPC stream we consider a "connection", which then must be reworked.

We can still make it atomic by doing some manual bookkeeping on top of the current protocol implementation using a mutex and a somewhat longlivier bbolt transaction.

**Comment by reinkrul** [comment]
Fixed in v2 with attached payloads.
