### ISSUE TITLE
RFC009: Provide Example of VP payload

### ISSUE THREAD

**Issue by jorritspee** [nuts-foundation/nuts-specification#67]
It would be nice to have an example of a VP payload, justice there is an example of a VC payload in RFC011.

**Comment by stevenvegt** [comment]
I agree we should add a non normative section where we can roughly explain the concepts of DIDs and VCs in relation to the Nuts node.

Note that you do not need to know and fully understand these specifications if you only want to use the nuts node. Therfor we put this on hold.

**Comment by woutslakhorst** [comment]
Currently RFC009 is a bit weird, it doesn't say a lot about VPs. We'll close this for now. 

In #80 we'll do something about RFC009
