### ISSUE TITLE
RFC006: Reference services

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-specification#78]
Introducing references in services to other services.
When the URI of a service consists of a reference, this must be resolvable to another endpoint.
Then end of the chain should be either a DID or a URL.

A ref is a cobination of a _target DID_ document combined with a _type_: `ref:${target}/serviceEndpoint/type?=${type}`

`ref:did:nuts:123/serviceEndpoint?type=eOverdracht`

References can point to other references with a limited depth.
Implementors of a resolver should follow all these references and return the Endpoint.

**Comment by reinkrul** [comment]
`{$ref: ""}` ?

**Comment by stevenvegt** [comment]
`ref://`

**Comment by woutslakhorst** [comment]
isn't `did:nuts:123/serviceEndpoint?type=eOverdracht` a reference as well?

It would mean that we can change the spec so a reference by did may also point to a compound endpoint and not just an absolute endpoint.
